project: 
  type: website
  
website:
  title: "Lipidomics analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: doc/learning.qmd
        text: "Report"
  page-footer:
    center:
      - text: "License: CC0 1.0"

format:
  html:
    theme: simplex

knitr:
  opts_chunk:
    echo: false

execute:
  freeze: auto
  echo: true

editor:
  markdown: 
    wrap: 72
    canonical: true
  
author:
  - name: Andreas
    orcid: 0000-0002-7559-1154
    email: andrlr@rm.dk
    url: https://pure.au.dk/portal/en/persons/andreas-gammelgaard-damsbo(e3c4afce-3eba-4456-8b8b-2fd90775c87a).html
    affiliations:
      - ref: dsc
affiliations:
  - id: dsc
    name: Danish Stroke Centre, AUH
    department: Neurology
    city: Aarhus
    country: Denmark
    url: https://www.en.auh.dk/departments/danish-stroke-centre/