---
title: "Draft analysis"
author: "Andreas Gammelgaard Damsbo"
format: html
execute:
  echo: true
editor:
  markdown: 
    wrap: 72
    canonical: true
---

## Setup and load data

```{r setup}
targets::tar_config_set(store = here::here("_targets"))
library(tidyverse)
library(targets)
library(tidymodels)
lipidomics <- tar_read(lipidomics)
```

## Results

```{r}
targets::tar_read(df_stats_by_metabolite) %>%
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>%
  select(Metabolite = metabolite, `Mean SD` = MeanSD, IQR = value_iqr) %>%
  knitr::kable(caption = "Descriptive statistics of the metabolites.")
```

```{r}
tar_read(fig_metabolites_distribution)
```

## Building the model

Parsnip

```{r}
log_reg_specs <- logistic_reg() |>
  set_engine("glm")
log_reg_specs
```

```{r}
lipidomics %>%
  count(code, metabolite) %>%
  filter(n > 1)
```

Recipe

```{r}
lipidomics_wide <- lipidomics |> metabolite_to_wider()

recipe(class ~ metabolite_cholesterol + age + gender, data = lipidomics_wide)

recipe(lipidomics_wide) %>%
  update_role(metabolite_lipid_ch_3_1, age, gender, new_role = "predictor") %>%
  update_role(class, new_role = "outcome") %>%
  step_normalize(starts_with("metabolite_"))

lipidomics_wide |> create_recipe_spec()

recipe_specs <- lipidomics_wide |>
  create_recipe_spec(metabolite_cholesterol)
```

```{r}
workflow() %>%
  add_model(log_reg_specs) %>%
  add_recipe(recipe_specs)
```

```{r}
create_model_workflow(
  logistic_reg() |>
    set_engine("glm"),
  lipidomics_wide |>
    create_recipe_spec(metabolite_cholesterol)
) |>
  fit(lipidomics_wide) |>
  tidy_model_output()
```
